CREATE DATABASE aula_mvc;
USE aula_mvc;

CREATE TABLE IF NOT EXISTS produtos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao TEXT,
preco DECIMAL(10,2) NOT NULL,
quantidade INT NOT NULL
);
